dist: trusty
os:
  - linux

before_install:
  - sudo apt-get install -y curl
addons:
  apt:
    update: true

install:
  - export TF_VER=0.11.7
  - export TF_OS=$(shell uname -s | tr '[:upper:]' '[:lower:]')
  - export TF_ARCH=$(shell uname -m | sed 's/x86_64/amd64/g')
  - export TF_URL=https://releases.hashicorp.com/terraform/$(TF_VER)/terraform_$(TF_VER)_$(TF_OS)_$(TF_ARCH).zip
  - curl '-#' -fL -o /tmp/terraform.zip $(TF_URL) 
  - unzip -q -d /tmp/ /tmp/terraform.zip
  - /tmp/terraform version

script:
  - /tmp/terraform plan
  - /tmp/terraform apply -auto-approve
  - /tmp/terraform destroy -auto-approve